name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    # I was getting errors when I used a CAPSLOCK tag, so I went with lowercase instead.
      run: docker build . --file Dockerfile-wrf_wps --tag wrf_wps:$(date +%s)
